pull_request_rules:
  - name: "Automatic merge github-actions[bot]'s PR"
    conditions:
      - or:
        - "author = github-actions[bot]"
        - "author = pre-commit-ci[bot]"
      - not: "conflict"
    actions:
      merge:
        method: squash
